#!/bin/bash

set -ex

exec 3>&1 # make stdout available as file descriptor 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export REPO_RESOURCE=repo
echo "Repo resource folder: [$1/${REPO_RESOURCE}]"

source $(dirname $0)/common.sh

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/vsts-resource-request.XXXXXX)

cat > $payload <&0

remote_commit_uri=$(jq -r '.params.remote_commit_uri // ""' < $payload)
vsts_user=$(jq -r '.params.vsts_user // ""' < $payload)
vsts_pat=$(jq -r '.params.vsts_pat // ""' < $payload)
vsts_account=$(jq -r '.params.vsts_account // ""' < $payload)
vsts_collection=$(jq -r '.params.vsts_collection // "DefaultCollection"' < $payload)
vsts_api_version=$(jq -r '.params.vsts_api_version // "1.0"' < $payload)


if [ -z "$remote_commit_uri" ]; then
    echo "remote_type other was specified. (missing remote_commit_uri: You must provide a uri for viewing commits)"
    exit 1
fi

if [ -z "$vsts_user" ]; then
  echo "invalid payload (missing missing username)"
  exit 1
fi

if [ -z "$vsts_pat" ]; then
  echo "invalid payload (missing personal access token)"
  exit 1
fi

if [ -z "$vsts_account" ]; then
  echo "invalid payload (missing vsts account name)"
  exit 1
fi

cd $1/repo

commit_sha=$(git log -1 --pretty=format:%H)
wit_id=$(git log -1 --pretty=format:%s | grep -e '\#[0-9]\+' | grep -e '[0-9]\+')

if [ -n "$wit_id" ]; then
  echo "No work item id detected.  Nothing to do.  Quitting."
  exit 0
fi

if [[ ${remote_commit_uri} == *"visualstudio.com"* ]]; then
    echo "TFS Git repo detected, attaching repo to work item"
    updateWitHistoryWithTfsGit "${vsts_account}" "${vsts_collection}" "${wit_id}" "${vsts_api_version}" "${commit_sha}" "${remote_commit_uri}"
else
    echo "External git repo detected, attaching repo to work item history"
    updateWitHistoryWithExternalGit "${vsts_account}" "${vsts_collection}" "${wit_id}" "${vsts_api_version}" "${commit_sha}" "${remote_commit_uri}"
fi
